apiVersion: v1
data:
  use-proxy-protocol: "true"
  log_format: main '$http_x_forwarded_for - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent "$http_referer" '
                 '"$http_user_agent"' ;
kind: ConfigMap
metadata:
  namespace: ingress-nginx
  name: nginx-configuration
