---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx
  strategy: {}
  template:
    metadata:
      labels:
        run: nginx
    spec:
      initContainers:
      - name: init
        image: busybox:latest
        command: ['/bin/sh', '-c', 'echo "Happy $(date "+%A")" > /web/index.html']
        volumeMounts:
        - mountPath: /web
          name: web-content
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        -name: nginx-port
         containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: web-content
        resources:
          limits:
            memory: 512M
          requests:
            memory: 512M
            cpu: .5
        readinessProbe:
          httpGet:
            path: /
            port: nginx-port
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: nginx-port
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: nginx-port
          periodSeconds: 5
      volumes:
      - name: web-content
        emptyDir: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 65

---
